# These are supported funding model platforms

github: ['PakkPoll', 'riz-ex', 'aryazakaria01', 'FeriEXP']
community_bridge: kennedy-project
custom: ['https://t.me/KennedyProject', 'https://t.me/EmikoSupport']
